# -*- coding: utf-8 -*-
"""Storage layer for the matching tool.

Two interchangeable backends:

* **SQLite** (default) — used for the local ``start.bat`` workflow, the test
  suite, and any run where no ``DATABASE_URL`` is configured.
* **PostgreSQL / Supabase** — activated automatically when ``DATABASE_URL``
  (or ``SUPABASE_DB_URL``) is present in the environment.

The rest of the app keeps using the small sqlite3-style surface it already
relies on — ``conn.execute(sql, params)`` returning a cursor with
``fetchone``/``fetchall``/``lastrowid``/``rowcount`` and a context manager that
commits on success. A thin wrapper makes psycopg2 behave the same way so no
call sites elsewhere need to know which backend is live.
"""
from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path

try:  # optional: load a local .env so start.bat picks up DATABASE_URL
    from dotenv import load_dotenv

    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
except Exception:  # noqa: BLE001 — dotenv is a convenience, never required
    pass

_raw_db_url = os.environ.get("DATABASE_URL") or os.environ.get("SUPABASE_DB_URL") or ""
# Tolerate a stray UTF-8 BOM / surrounding whitespace — these creep in when the
# value is piped into the env or copy-pasted into a dashboard, and psycopg2
# rejects a DSN with a leading BOM ("missing = after ...").
DATABASE_URL = _raw_db_url.strip().encode("utf-8").decode("utf-8-sig").strip() or None

DB_PATH = os.environ.get("PBK_DB") or str(
    Path(__file__).resolve().parent.parent / "data" / "pbk.db")

# ``PBK_DB`` explicitly pins the SQLite backend — the test suite always sets it,
# so tests never touch a configured Postgres/Supabase database even if a local
# .env defines DATABASE_URL. Postgres is used only when DATABASE_URL is present
# AND PBK_DB is unset (the production / Vercel case).
USE_PG = bool(DATABASE_URL) and not os.environ.get("PBK_DB")

if USE_PG:
    import psycopg2
    import psycopg2.extras

    IntegrityError = psycopg2.IntegrityError
    _PK = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    _REAL = "DOUBLE PRECISION"
    _NOW = "(now())::text"
else:
    IntegrityError = sqlite3.IntegrityError
    _PK = "INTEGER PRIMARY KEY AUTOINCREMENT"
    _REAL = "REAL"
    _NOW = "(datetime('now'))"

_LINE_COLUMNS = f"""
    id {_PK},
    invoice_date TEXT,
    invoice_no TEXT DEFAULT '',
    party TEXT DEFAULT '',
    item TEXT DEFAULT '',
    qty {_REAL} NOT NULL DEFAULT 0,
    unit_price {_REAL} NOT NULL DEFAULT 0,
    vat {_REAL} NOT NULL DEFAULT 0,
    doc_type TEXT NOT NULL DEFAULT 'i',
    source TEXT NOT NULL DEFAULT 'manual',
    eta_uuid TEXT,
    eta_line_index INTEGER,
    created_at TEXT DEFAULT {_NOW}
"""

SCHEMA = f"""
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);
CREATE TABLE IF NOT EXISTS purchase_lines (
    {_LINE_COLUMNS},
    UNIQUE(eta_uuid, eta_line_index)
);
CREATE TABLE IF NOT EXISTS sale_lines (
    {_LINE_COLUMNS},
    internal_ref TEXT DEFAULT '',
    note TEXT DEFAULT '',
    UNIQUE(eta_uuid, eta_line_index)
);
CREATE TABLE IF NOT EXISTS match_groups (
    id {_PK},
    note TEXT DEFAULT '',
    created_at TEXT DEFAULT {_NOW}
);
CREATE TABLE IF NOT EXISTS match_group_purchases (
    group_id INTEGER NOT NULL REFERENCES match_groups(id) ON DELETE CASCADE,
    purchase_line_id INTEGER NOT NULL UNIQUE REFERENCES purchase_lines(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, purchase_line_id)
);
CREATE TABLE IF NOT EXISTS match_group_sales (
    group_id INTEGER NOT NULL REFERENCES match_groups(id) ON DELETE CASCADE,
    sale_line_id INTEGER NOT NULL UNIQUE REFERENCES sale_lines(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, sale_line_id)
);
"""


# --------------------------------------------------------------------------- PG shim
# Tables with an auto-increment ``id`` — only these get an auto ``RETURNING id``
# appended so ``cursor.lastrowid`` works like SQLite. ``settings`` is excluded
# (its primary key is ``key``, it has no ``id`` column).
_ID_TABLES = {"purchase_lines", "sale_lines", "match_groups"}
_INSERT_TABLE = re.compile(r"^\s*INSERT\s+INTO\s+([^\s(]+)", re.IGNORECASE)


class _PgCursor:
    """Wraps a psycopg2 cursor to expose the sqlite3 attributes we use."""

    def __init__(self, cur):
        self._cur = cur
        self.lastrowid = None

    @property
    def rowcount(self) -> int:
        return self._cur.rowcount

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def __iter__(self):
        # sqlite3 cursors are iterable (yield rows); psycopg2 cursors are too —
        # callers do `for row in conn.execute(...)`, so mirror that.
        return iter(self._cur)


class _PgConn:
    """A sqlite3.Connection look-alike backed by psycopg2.

    ``execute`` translates ``?`` placeholders to ``%s`` and, for plain INSERTs,
    appends ``RETURNING id`` so ``cursor.lastrowid`` works like SQLite. Used as
    a context manager it commits on success and rolls back on error, mirroring
    sqlite3's behaviour.
    """

    def __init__(self, dsn: str):
        self._conn = psycopg2.connect(
            dsn, cursor_factory=psycopg2.extras.RealDictCursor)

    def execute(self, sql: str, params=()):
        pg_sql = sql.replace("?", "%s")
        cur = self._conn.cursor()
        wrapped = _PgCursor(cur)
        m = _INSERT_TABLE.match(pg_sql)
        wants_id = (m is not None and m.group(1).lower() in _ID_TABLES
                    and "RETURNING" not in pg_sql.upper())
        cur.execute(pg_sql + (" RETURNING id" if wants_id else ""), params or ())
        if wants_id and cur.rowcount:
            row = cur.fetchone()
            if row is not None:
                wrapped.lastrowid = row["id"]
        return wrapped

    def executescript(self, script: str):
        with self._conn.cursor() as cur:
            cur.execute(script)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type:
            self._conn.rollback()
        else:
            self._conn.commit()
        self._conn.close()
        return False


def get_conn():
    if USE_PG:
        return _PgConn(DATABASE_URL)
    Path(DB_PATH).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=15)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db():
    with get_conn() as conn:
        conn.executescript(SCHEMA)


def get_setting(key: str, default: str = "") -> str:
    with get_conn() as conn:
        row = conn.execute("SELECT value FROM settings WHERE key=?", (key,)).fetchone()
    return row["value"] if row and row["value"] is not None else default


def set_setting(key: str, value: str):
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO settings(key,value) VALUES(?,?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value", (key, value))


def vat_rate() -> float:
    try:
        return float(get_setting("vat_rate", "0.14"))
    except ValueError:
        return 0.14
